language: ruby
services: postgresql
rvm:
  - 2.0.0
  
before_script:
  - psql -c 'create database myapp_test;' -U postgres
  
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec