FORMAT: 1A
HOST: http://api.flaredown.com

# Flaredown
Flaredown is a chronic illness management tool

## Group Entry

Entries are json documents that contain all the responses and results
associated with a Flaredown user "check-in" and have the following 
possible attributes.

- id
- date
- catalogs 
- catalog_definitions
- responses
- treatments
- scores

Depending on action, only specific attributes are included (e.g. `catalog_definitions` for new entries,
`responses` and `scores` for existing entry lookup.
 

## Entries [/v1/entries/{date}]
+ Parameters
    + date (required, string, `2014-08-13`) ... A date string in the format YYYY-MM-DD
    
### Get an Entry [GET]
+ Response 200 (application/json)

        "entry": {   
            "id": "abc123", 
            "date": "2014-08-13",
            "catalogs": ["hbi"],
            "responses": [
                {
                    "id": "hbi_general_well_being_abc123",
                    "name": "general_well_being",
                    "value": 2,
                    "catalog": "hbi"
                },
                {
                    "id": "hbi_ab_pain_abc123",
                    "name": "ab_pain",
                    "value": 3,
                    "catalog": "hbi"
                },
                {
                    "id": "hbi_stools_abc123",
                    "name": "stools",
                    "value": 1,
                    "catalog": "hbi"
                },
                {
                    "id": "hbi_ab_mass_abc123",
                    "name": "ab_mass",
                    "value": 3,
                    "catalog": "hbi"
                },
                {
                    "id": "hbi_complication_uveitis_abc123",
                    "name": "complication_uveitis",
                    "value": 1,
                    "catalog": "hbi"
                },
                {
                    "id": "hbi_complication_abscess_abc123",
                    "name": "complication_abscess",
                    "value": 0,
                    "catalog": "hbi"
                }
            ],
            "treatments": [
                {
                    "id": "dihydrogen_monoxide_1_liter_abc123",
                    "name": "Dihydrogen monoxide",
                    "quantity": "1",
                    "unit": "liter"
                }
            ],
            "scores": [
                {
                "id": "hbi_abc123",
                "name": "hbi",
                "value": 10
                }
            ]
        }


### Update an Entry [PUT]
+ Response 200 (application/json)

        "entry": {   
            "id": "abc123", 
            "date": "2014-08-13",
            "catalogs": ["hbi"],
            "responses": [
                {
                    "name": "general_well_being",
                    "value": 3,
                    "catalog": "hbi"
                }
            ],
            "treatments": [
                {
                    "id": "dihydrogen_monoxide_1_liter_abc123",
                    "name": "Dihydrogen monoxide",
                    "quantity": "1",
                    "unit": "liter"
                }
            ]
        }

### New Entry [POST]
Creates a new Entry for the specified date or returns an existing one. 
This endpoint is unique in that it returns the `catalog` `definitions` along with 
the the `entry`. In this way it should always be used to start the "check-in"
process even if the `entry` exists so that the frontend knows how to build
the form.

`catalogs` are automatically included based on the `User`s current subsscriptions.
    
+ Request (application/json)

        { date: "2014-08-13" }

+ Response 201 (application/json)

        "entry": { 
            "id": "abc123", 
            "date": "2014-08-13",
            "catalogs": ["hbi"],
            "catalog_definitions": {
                "hbi": {
                    "ab_mass": [
                        {
                            "inputs": [
                                {
                                    "helper": null,
                                    "label": "none",
                                    "meta_label": "happy_face",
                                    "value": 0
                                },
                                {
                                    "helper": null,
                                    "label": "dubious",
                                    "meta_label": "neutral_face",
                                    "value": 1
                                },
                                {
                                    "helper": null,
                                    "label": "definite",
                                    "meta_label": "frowny_face",
                                    "value": 2
                                },
                                {
                                    "helper": null,
                                    "label": "definite_and_tender",
                                    "meta_label": "sad_face",
                                    "value": 3
                                }
                            ],
                            "kind": "select",
                            "name": "ab_mass",
                            "section": 3
                        }
                    ],
                    "ab_pain": [
                        {
                            "inputs": [
                                {
                                    "helper": null,
                                    "label": "none",
                                    "meta_label": "happy_face",
                                    "value": 0
                                },
                                {
                                    "helper": null,
                                    "label": "mild",
                                    "meta_label": "neutral_face",
                                    "value": 1
                                },
                                {
                                    "helper": null,
                                    "label": "moderate",
                                    "meta_label": "frowny_face",
                                    "value": 2
                                },
                                {
                                    "helper": null,
                                    "label": "severe",
                                    "meta_label": "sad_face",
                                    "value": 3
                                }
                            ],
                            "kind": "select",
                            "name": "ab_pain",
                            "section": 1
                        }
                    ],
                    "complications": [
                        {
                            "kind": "checkbox",
                            "name": "complication_arthralgia",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_uveitis",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_erythema_nodosum",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_aphthous_ulcers",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_anal_fissure",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_fistula",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_abscess",
                            "section": 4
                        }
                    ],
                    "general_well_being": [
                        {
                            "inputs": [
                                {
                                    "helper": null,
                                    "label": "very_well",
                                    "meta_label": "happy_face",
                                    "value": 0
                                },
                                {
                                    "helper": null,
                                    "label": "slightly_below_par",
                                    "meta_label": "neutral_face",
                                    "value": 1
                                },
                                {
                                    "helper": null,
                                    "label": "poor",
                                    "meta_label": "frowny_face",
                                    "value": 2
                                },
                                {
                                    "helper": null,
                                    "label": "very_poor",
                                    "meta_label": "sad_face",
                                    "value": 3
                                },
                                {
                                    "helper": null,
                                    "label": "terrible",
                                    "meta_label": "sad_face",
                                    "value": 4
                                }
                            ],
                            "kind": "select",
                            "name": "general_well_being",
                            "section": 0
                        }
                    ],
                    "stools": [
                        {
                            "inputs": [
                                {
                                    "helper": "stools_daily",
                                    "label": null,
                                    "meta_label": null,
                                    "value": 0
                                }
                            ],
                            "kind": "number",
                            "name": "stools",
                            "section": 2
                        }
                    ]
                }
            }

+ Response 200 (application/json)

        "entry": { 
            "id": "abc123",
            "date": "2014-08-13",
            "catalogs": ["hbi"],
            "catalog_definitions": {
                "hbi": {
                    "ab_mass": [
                        {
                            "inputs": [
                                {
                                    "helper": null,
                                    "label": "none",
                                    "meta_label": "happy_face",
                                    "value": 0
                                },
                                {
                                    "helper": null,
                                    "label": "dubious",
                                    "meta_label": "neutral_face",
                                    "value": 1
                                },
                                {
                                    "helper": null,
                                    "label": "definite",
                                    "meta_label": "frowny_face",
                                    "value": 2
                                },
                                {
                                    "helper": null,
                                    "label": "definite_and_tender",
                                    "meta_label": "sad_face",
                                    "value": 3
                                }
                            ],
                            "kind": "select",
                            "name": "ab_mass",
                            "section": 3
                        }
                    ],
                    "ab_pain": [
                        {
                            "inputs": [
                                {
                                    "helper": null,
                                    "label": "none",
                                    "meta_label": "happy_face",
                                    "value": 0
                                },
                                {
                                    "helper": null,
                                    "label": "mild",
                                    "meta_label": "neutral_face",
                                    "value": 1
                                },
                                {
                                    "helper": null,
                                    "label": "moderate",
                                    "meta_label": "frowny_face",
                                    "value": 2
                                },
                                {
                                    "helper": null,
                                    "label": "severe",
                                    "meta_label": "sad_face",
                                    "value": 3
                                }
                            ],
                            "kind": "select",
                            "name": "ab_pain",
                            "section": 1
                        }
                    ],
                    "complications": [
                        {
                            "kind": "checkbox",
                            "name": "complication_arthralgia",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_uveitis",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_erythema_nodosum",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_aphthous_ulcers",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_anal_fissure",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_fistula",
                            "section": 4
                        },
                        {
                            "kind": "checkbox",
                            "name": "complication_abscess",
                            "section": 4
                        }
                    ],
                    "general_well_being": [
                        {
                            "inputs": [
                                {
                                    "helper": null,
                                    "label": "very_well",
                                    "meta_label": "happy_face",
                                    "value": 0
                                },
                                {
                                    "helper": null,
                                    "label": "slightly_below_par",
                                    "meta_label": "neutral_face",
                                    "value": 1
                                },
                                {
                                    "helper": null,
                                    "label": "poor",
                                    "meta_label": "frowny_face",
                                    "value": 2
                                },
                                {
                                    "helper": null,
                                    "label": "very_poor",
                                    "meta_label": "sad_face",
                                    "value": 3
                                },
                                {
                                    "helper": null,
                                    "label": "terrible",
                                    "meta_label": "sad_face",
                                    "value": 4
                                }
                            ],
                            "kind": "select",
                            "name": "general_well_being",
                            "section": 0
                        }
                    ],
                    "stools": [
                        {
                            "inputs": [
                                {
                                    "helper": "stools_daily",
                                    "label": null,
                                    "meta_label": null,
                                    "value": 0
                                }
                            ],
                            "kind": "number",
                            "name": "stools",
                            "section": 2
                        }
                    ]
                }
            },
            "treatments": [
                {
                    "id": "dihydrogen_monoxide_1_liter_abc123",
                    "name": "Dihydrogen monoxide",
                    "quantity": "1",
                    "unit": "liter"
                }
            ],
            "responses": [
                {
                    "id": "ab_pain_abc123",
                    "name": "ab_pain",
                    "value": 3
                }
            ]
        }
