development:
  adapter: postgresql
  encoding: unicode
  database: cdai_development
  pool: 5
  host: localhost
  user: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: cdai_test
  pool: 5
  host: localhost
  user: postgres