development:
  adapter: postgresql
  encoding: unicode
  database: flaredown_development
  pool: 5
  host: localhost
  user: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: flaredown_test
  pool: 5
  host: localhost
  user: postgres
  password: password