# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

u=User.create(email: "test@test.com", password: "testing123", password_confirmation: "testing123", gender: "male", weight: 145)

Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 1}, {name: "general", response: 4}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: true}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 2}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 140}], date: Time.now-17.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 4}, {name: "ab_pain", response: 1}, {name: "general", response: 4}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: true}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: true}, {name: "mass", response: 5}, {name: "hematocrit", response: 50}, {name: "weight_current", response: 150}], date: Time.now-16.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 1}, {name: "ab_pain", response: 1}, {name: "general", response: 3}, {name: "complication_arthritis", response: false}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 5}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 140}], date: Time.now-15.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 2}, {name: "general", response: 4}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: true}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: true}, {name: "opiates",  response: true}, {name: "mass", response: 5}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 130}], date: Time.now-14.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 2}, {name: "general", response: 4}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 0}, {name: "hematocrit", response: 38}, {name: "weight_current", response: 140}], date: Time.now-13.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 3}, {name: "ab_pain", response: 1}, {name: "general", response: 4}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: true}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: true}, {name: "mass", response: 0}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 140}], date: Time.now-12.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 2}, {name: "general", response: 3}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 5}, {name: "hematocrit", response: 44}, {name: "weight_current", response: 110}], date: Time.now-11.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 3}, {name: "ab_pain", response: 3}, {name: "general", response: 2}, {name: "complication_arthritis", response: false}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: true}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 2}, {name: "hematocrit", response: 43}, {name: "weight_current", response: 140}], date: Time.now-10.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 4}, {name: "general", response: 2}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: true}, {name: "mass", response: 5}, {name: "hematocrit", response: 42}, {name: "weight_current", response: 140}], date: Time.now-9.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 1}, {name: "ab_pain", response: 4}, {name: "general", response: 2}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: true}, {name: "complication_erythema", response: true}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: true}, {name: "opiates",  response: false}, {name: "mass", response: 2}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 140}], date: Time.now-8.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 1}, {name: "ab_pain", response: 3}, {name: "general", response: 1}, {name: "complication_arthritis", response: false}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 2}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 120}], date: Time.now-7.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 2}, {name: "general", response: 1}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: true}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 5}, {name: "hematocrit", response: 48}, {name: "weight_current", response: 140}], date: Time.now-6.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 3}, {name: "general", response: 1}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 0}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 150}], date: Time.now-5.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 4}, {name: "ab_pain", response: 1}, {name: "general", response: 1}, {name: "complication_arthritis", response: false}, {name: "complication_iritis", response: true}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: true}, {name: "mass", response: 5}, {name: "hematocrit", response: 56}, {name: "weight_current", response: 140}], date: Time.now-4.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 4}, {name: "ab_pain", response: 2}, {name: "general", response: 2}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: true}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: true}, {name: "opiates",  response: false}, {name: "mass", response: 5}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 130}], date: Time.now-3.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 3}, {name: "ab_pain", response: 1}, {name: "general", response: 2}, {name: "complication_arthritis", response: false}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 5}, {name: "hematocrit", response: 52}, {name: "weight_current", response: 140}], date: Time.now-2.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 1}, {name: "general", response: 4}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: true}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 2}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 140}], date: Time.now-1.day)
Entry.create(user: u, catalogs: ["cdai"], questions: [{name: "stools", response: 2}, {name: "ab_pain", response: 3}, {name: "general", response: 2}, {name: "complication_arthritis", response: true}, {name: "complication_iritis", response: false}, {name: "complication_erythema", response: false}, {name: "complication_fistula", response: false}, {name: "complication_fever", response: true}, {name: "complication_other_fistula", response: false}, {name: "opiates",  response: false}, {name: "mass", response: 5}, {name: "hematocrit", response: 40}, {name: "weight_current", response: 140}], date: Time.now)