# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Entry.create(stools: 2, ab_pain: 1, general: 4, complication_arthritis: true, complication_iritis: false, complication_erythema: true, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 2, hematocrit: 40, weight_current: 140)
Entry.create(stools: 4, ab_pain: 1, general: 4, complication_arthritis: true, complication_iritis: true, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: true, mass: 5, hematocrit: 50, weight_current: 150)
Entry.create(stools: 1, ab_pain: 1, general: 3, complication_arthritis: false, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 5, hematocrit: 40, weight_current: 140)
Entry.create(stools: 2, ab_pain: 2, general: 4, complication_arthritis: true, complication_iritis: false, complication_erythema: true, complication_fistula: false, complication_fever: true, complication_other_fistula: true, opiates: true, mass: 5, hematocrit: 40, weight_current: 130)
Entry.create(stools: 2, ab_pain: 2, general: 4, complication_arthritis: true, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 0, hematocrit: 38, weight_current: 140)
Entry.create(stools: 3, ab_pain: 1, general: 4, complication_arthritis: true, complication_iritis: true, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: true, mass: 0, hematocrit: 40, weight_current: 140)
Entry.create(stools: 2, ab_pain: 2, general: 3, complication_arthritis: true, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 5, hematocrit: 44, weight_current: 110)
Entry.create(stools: 3, ab_pain: 3, general: 2, complication_arthritis: false, complication_iritis: false, complication_erythema: true, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 2, hematocrit: 43, weight_current: 140)
Entry.create(stools: 2, ab_pain: 4, general: 2, complication_arthritis: true, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: true, mass: 5, hematocrit: 42, weight_current: 140)
Entry.create(stools: 1, ab_pain: 4, general: 2, complication_arthritis: true, complication_iritis: true, complication_erythema: true, complication_fistula: false, complication_fever: true, complication_other_fistula: true, opiates: false, mass: 2, hematocrit: 40, weight_current: 140)
Entry.create(stools: 1, ab_pain: 3, general: 1, complication_arthritis: false, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 2, hematocrit: 40, weight_current: 120)
Entry.create(stools: 2, ab_pain: 2, general: 1, complication_arthritis: true, complication_iritis: true, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 5, hematocrit: 48, weight_current: 140)
Entry.create(stools: 2, ab_pain: 3, general: 1, complication_arthritis: true, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 0, hematocrit: 40, weight_current: 150)
Entry.create(stools: 4, ab_pain: 1, general: 1, complication_arthritis: false, complication_iritis: true, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: true, mass: 5, hematocrit: 56, weight_current: 140)
Entry.create(stools: 4, ab_pain: 2, general: 2, complication_arthritis: true, complication_iritis: false, complication_erythema: true, complication_fistula: false, complication_fever: true, complication_other_fistula: true, opiates: false, mass: 5, hematocrit: 40, weight_current: 130)
Entry.create(stools: 3, ab_pain: 1, general: 2, complication_arthritis: false, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 5, hematocrit: 52, weight_current: 140)
Entry.create(stools: 2, ab_pain: 1, general: 4, complication_arthritis: true, complication_iritis: true, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 2, hematocrit: 40, weight_current: 140)
Entry.create(stools: 2, ab_pain: 3, general: 2, complication_arthritis: true, complication_iritis: false, complication_erythema: false, complication_fistula: false, complication_fever: true, complication_other_fistula: false, opiates: false, mass: 5, hematocrit: 40, weight_current: 140)
